name: Release
on:
  push:
    tags:
      - 'v*'

env:
  GO_VERSION: stable

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [amd64, arm64]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get -qq update
          sudo apt-get install -y --no-install-recommends \
            build-essential \
            gcc-aarch64-linux-gnu \
            libc6-dev-arm64-cross \
            gcc-mingw-w64

      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install mingw

      - name: Install dependencies (MacOS)
        if: runner.os == 'macOS'
        run: brew install gcc

      - name: Build
        env:
          CGO_ENABLED: 1
          GOOS: ${{ runner.os == 'Windows' && 'windows' || runner.os == 'Linux' && 'linux' || 'darwin' }}
          GOARCH: ${{ matrix.arch }}
          CC: ${{ matrix.os == 'macOS' && 'clang' || matrix.arch == 'arm64' && 'aarch64-linux-gnu-gcc' || 'gcc' }}
        run: |
          go build -o myapp-${{ runner.os }}-${{ matrix.arch }}

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: myapp-${{ runner.os }}-${{ matrix.arch }}
          path: myapp-*

